[2024-02-29 14:37:15,996] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_redshift.insertar_en_tabla scheduled__2022-09-20T03:00:00+00:00 [queued]>
[2024-02-29 14:37:16,026] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_redshift.insertar_en_tabla scheduled__2022-09-20T03:00:00+00:00 [queued]>
[2024-02-29 14:37:16,032] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 14:37:16,034] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-02-29 14:37:16,039] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 14:37:16,111] {taskinstance.py:1397} INFO - Executing <Task(RedshiftSQLOperator): insertar_en_tabla> on 2022-09-20 03:00:00+00:00
[2024-02-29 14:37:16,127] {standard_task_runner.py:52} INFO - Started process 825 to run task
[2024-02-29 14:37:16,136] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_redshift', 'insertar_en_tabla', 'scheduled__2022-09-20T03:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres_database.py', '--cfg-path', '/tmp/tmpianpvw38', '--error-file', '/tmp/tmpobdkw6zo']
[2024-02-29 14:37:16,148] {standard_task_runner.py:80} INFO - Job 101: Subtask insertar_en_tabla
[2024-02-29 14:37:16,321] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_redshift.insertar_en_tabla scheduled__2022-09-20T03:00:00+00:00 [running]> on host 85ed7e7789a6
[2024-02-29 14:37:16,585] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Joaco
AIRFLOW_CTX_DAG_ID=dag_con_conexion_redshift
AIRFLOW_CTX_TASK_ID=insertar_en_tabla
AIRFLOW_CTX_EXECUTION_DATE=2022-09-20T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-20T03:00:00+00:00
[2024-02-29 14:37:16,586] {redshift_sql.py:76} INFO - Executing statement: 
            insert into fin_mundo (dt,pais) values ('12-12-2025','Colombia');
        
        
[2024-02-29 14:37:16,605] {base.py:68} INFO - Using connection ID 'redshift_keys' for task execution.
[2024-02-29 14:37:18,130] {dbapi.py:231} INFO - Running statement: 
            insert into fin_mundo (dt,pais) values ('12-12-2025','Colombia');
        
        , parameters: None
[2024-02-29 14:37:18,578] {dbapi.py:239} INFO - Rows affected: 1
[2024-02-29 14:37:18,593] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_con_conexion_redshift, task_id=insertar_en_tabla, execution_date=20220920T030000, start_date=20240229T143715, end_date=20240229T143718
[2024-02-29 14:37:18,640] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-29 14:37:18,668] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
