[2024-02-29 14:37:27,448] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_redshift.insertar_en_tabla scheduled__2022-10-09T03:00:00+00:00 [queued]>
[2024-02-29 14:37:27,508] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_redshift.insertar_en_tabla scheduled__2022-10-09T03:00:00+00:00 [queued]>
[2024-02-29 14:37:27,518] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 14:37:27,530] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-02-29 14:37:27,535] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 14:37:27,613] {taskinstance.py:1397} INFO - Executing <Task(RedshiftSQLOperator): insertar_en_tabla> on 2022-10-09 03:00:00+00:00
[2024-02-29 14:37:27,628] {standard_task_runner.py:52} INFO - Started process 896 to run task
[2024-02-29 14:37:27,640] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_redshift', 'insertar_en_tabla', 'scheduled__2022-10-09T03:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres_database.py', '--cfg-path', '/tmp/tmpi7nqst92', '--error-file', '/tmp/tmpm75hluow']
[2024-02-29 14:37:27,643] {standard_task_runner.py:80} INFO - Job 135: Subtask insertar_en_tabla
[2024-02-29 14:37:27,754] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_redshift.insertar_en_tabla scheduled__2022-10-09T03:00:00+00:00 [running]> on host 85ed7e7789a6
[2024-02-29 14:37:27,899] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Joaco
AIRFLOW_CTX_DAG_ID=dag_con_conexion_redshift
AIRFLOW_CTX_TASK_ID=insertar_en_tabla
AIRFLOW_CTX_EXECUTION_DATE=2022-10-09T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-09T03:00:00+00:00
[2024-02-29 14:37:27,900] {redshift_sql.py:76} INFO - Executing statement: 
            insert into fin_mundo (dt,pais) values ('12-12-2025','Colombia');
        
        
[2024-02-29 14:37:27,913] {base.py:68} INFO - Using connection ID 'redshift_keys' for task execution.
[2024-02-29 14:37:29,331] {dbapi.py:231} INFO - Running statement: 
            insert into fin_mundo (dt,pais) values ('12-12-2025','Colombia');
        
        , parameters: None
[2024-02-29 14:37:29,781] {dbapi.py:239} INFO - Rows affected: 1
[2024-02-29 14:37:29,798] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_con_conexion_redshift, task_id=insertar_en_tabla, execution_date=20221009T030000, start_date=20240229T143727, end_date=20240229T143729
[2024-02-29 14:37:29,858] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-29 14:37:29,906] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
